### ISSUE TITLE
Examples for common use-cases

### ISSUE THREAD

**Issue by jonhoo** [crate-ci/azure-pipelines#78]
We recently made the decision to have this repository provide building blocks for CI (and a single, "80%" default template), since we found it too difficult to expose all the various ways in which people want their CI builds to vary. However, this repository can still serve as a convenient reference for how to implement particularly common patterns in your own CI scripts.

Here are some examples we should probably provide (PRs welcome!):

 - [ ] Producing GitHub artifacts (#23)
 - [ ] How to enable caching (#36)
 - [ ] Uploading documentation to GitHub pages (#35)
 - [ ] Producing crates.io releases (#34)

If you have others, please post here and I'll add them!
